backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: USPS, name: usps, widget: object, fields: [{label: Usp 1, name: usp1, widget: string},{label: Usp 2, name: usp2, widget: string},{label: Usp 3, name: usp3, widget: string}]}
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields: [
                {label: Titel, name: title, widget: string},
                {label: Text, name: text, widget: markdown},
                {label: Openingstijden, name: openinghours, widget: object, fields: [
                  {label: Maandag, name: monday, widget: object, fields: [
                    {label: Open?, name: monOpen, widget: "boolean", default: true},
                    {label: Open om, name: monOpenAt, widget: string},
                    {label: Gesloten om, name: monClosedAt, widget: string},
                  ]},
                  {label: Dinsdag, name: tuesday, widget: object, fields: [
                    {label: Open?, name: tueOpen, widget: "boolean", default: true},
                    {label: Open om, name: tueOpenAt, widget: string},
                    {label: Gesloten om, name: tueClosedAt, widget: string},
                  ]},
                  {label: Woensdag, name: wednesday, widget: object, fields: [
                    {label: Open?, name: wedOpen, widget: "boolean", default: true},
                    {label: Open om, name: wedOpenAt, widget: string},
                    {label: Gesloten om, name: wedClosedAt, widget: string},
                  ]},
                  {label: Donderdag, name: thursday, widget: object, fields: [
                    {label: Open?, name: thurOpen, widget: "boolean", default: true},
                    {label: Open om, name: thurOpenAt, widget: string},
                    {label: Gesloten om, name: thurClosedAt, widget: string},
                  ]},
                  {label: Vrijdag, name: friday, widget: object, fields: [
                    {label: Open?, name: friOpen, widget: "boolean", default: true},
                    {label: Open om, name: friOpenAt, widget: string},
                    {label: Gesloten om, name: friClosedAt, widget: string},
                  ]},
                  {label: Zaterdag, name: saturday, widget: object, fields: [
                    {label: Open?, name: satOpen, widget: "boolean", default: true},
                    {label: Open om, name: satOpenAt, widget: string},
                    {label: Gesloten om, name: satClosedAt, widget: string},
                  ]},
                  {label: Zondag, name: sunday, widget: object, fields: [
                    {label: Open?, name: sunOpen, widget: "boolean", default: true},
                    {label: Open om, name: sunOpenAt, widget: string},
                    {label: Gesloten om, name: sunClosedAt, widget: string},
                  ]},
                ]}
              ]}
          - {label: Extra Info, name: extrainfo, widget: text},
          - {
              label: Sfeerimpressie,
              name: impressions,
              widget: object,
              fields: [
                {label: Rij, name: row, widget: list, fields: [
                  {label: Afbeeldingen, name: images, widget: list, fields: [
                    {label: Afbeelding, name: image, widget: image},
                  ]}
                ]}
              ]}
          - {
              label: Waarom TopTuinDeals?,
              name: storeUsps,
              widget: object,
              fields: [
                  {label: USP 1, name: usp1, widget: object, fields: [
                    {label: Titel, name: title, widget: string},
                    {label: Text, name: text, widget: text},
                  ]},
                  {label: USP 2, name: usp2, widget: object, fields: [
                    {label: Titel, name: title, widget: string},
                    {label: Text, name: text, widget: text},
                  ]},
                  {label: USP 3, name: usp3, widget: object, fields: [
                    {label: Titel, name: title, widget: string},
                    {label: Text, name: text, widget: text},
                  ]},
                  {label: Afbeelding, name: uspImage, widget: image}
              ]}
          - {
              label: Laatste Berichten,
              name: latestMessages,
              widget: object,
              fields: [
                {label: Berichten, name: messages, widget: list, fields: [
                  {label: Bericht, name: message, widget: text},
                  {label: Afbeelding, name: messageImage, widget: image},
                ]}
              ]}
          - {
              label: Locatie,
              name: location,
              widget: object,
              fields: [
                {label: Titel, name: title, widget: text},
                {label: Intro, name: intro, widget: text},
                {label: Adres, name: address, widget: text},
                {label: Telefoon, name: phone, widget: text}
              ]}
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields: [
                {label: Titel, name: title, widget: text},
                {label: Intro, name: intro, widget: text}
              ]}